dataset:
    path: /syntax_finetuning/src/data/dataset_simple_rel/syntagrus/ru_simple_syntagrus_grct_test.json
    name: grct_gsd
    representation_type: grct

models:
  - original_model_id: models/Qwen3-0.6B-Base
    peft_group:
      - ../syntax_finetuning_adapters/Qwen3_0_6B_Base_syntagrus_grct_seed10_ep2
      - ../syntax_finetuning_adapters/Qwen3_0_6B_Base_syntagrus_grct_seed10_ep3
      - ../syntax_finetuning_adapters/Qwen3_0_6B_Base_syntagrus_grct_seed200_ep2
      - ../syntax_finetuning_adapters/Qwen3_0_6B_Base_syntagrus_grct_seed200_ep3      
    is_instruct: False
    model_library: vllm
    max_tokens: 1500
  - original_model_id: models/Qwen3-0.6B-Base
    peft_group:
      - ../syntax_finetuning_adapters/Qwen3_0_6B_syntagrus_grct_seed10_ep2
      - ../syntax_finetuning_adapters/Qwen3_0_6B_syntagrus_grct_seed10_ep3
      - ../syntax_finetuning_adapters/Qwen3_0_6B_syntagrus_grct_seed200_ep2
      - ../syntax_finetuning_adapters/Qwen3_0_6B_syntagrus_grct_seed200_ep3      
    is_instruct: False
    model_library: vllm
    max_tokens: 1500
output_dir: /syntax_finetuning_pred_results
