batch_size: 16
micro_batch_size: 4
dataset_config:
- dev_file_path: /syntax_finetuning/src/data/dataset_simple_rel/syntagrus/ru_simple_syntagrus_conll_short_dev.json
  train_file_path: /syntax_finetuning/src/data/dataset_simple_rel/syntagrus/ru_simple_syntagrus_conll_short_train.json
  treebank: syntagrus_conll_short
epochs: 5
model_config:
  - is_instruct: true
    model_name: /models/RuadaptQwen3-4B-Hybrid
    per_device_eval_batch_size: 2
    torch_empty_cache_steps: True
root_output_dir_path: /adapters/conll_short_ruadapt4
eval_steps: 500
cutoff_len: 1500
learning_rate:
  - 0.00001
init_lora_weights: loftq
save_epoch_adapters: True
seed:
- 10
- 200
- 3000
